<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1536216895787' stop='1536216899927'>
    <name>Login suit:</name>
    <title>Login suit:</title>
    <test-cases>
        <test-case start='1536216895788' status='pending' stop='1536216895790'>
            <name>Login pass test</name>
            <title>Login pass test</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Temporarily disabled with xit</message>
                <stack-trace></stack-trace>
            </failure>
        </test-case>
        <test-case start='1536216895790' status='failed' stop='1536216899927'>
            <name>Login pass test</name>
            <title>Login pass test</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Failed: No element found using locator: By(css selector, div.form-group > a.section-body__actions >span:nth-child(2))</message>
                <stack-trace>NoSuchElementError: No element found using locator: By(css selector, div.form-group > a.section-body__actions >span:nth-child(2))
                    at elementArrayFinder.getWebElements.then (E:\allure\qa_automation_camp\node_modules\protractor\built\element.js:814:27)
                    at ManagedPromise.invokeCallback_ (E:\allure\qa_automation_camp\node_modules\selenium-webdriver\lib\promise.js:1376:14)
                    at TaskQueue.execute_ (E:\allure\qa_automation_camp\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (E:\allure\qa_automation_camp\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at asyncRun (E:\allure\qa_automation_camp\node_modules\selenium-webdriver\lib\promise.js:2927:27)
                    at E:\allure\qa_automation_camp\node_modules\selenium-webdriver\lib\promise.js:668:7
                    at process._tickCallback (internal/process/next_tick.js:68:7)Error
                    at ElementArrayFinder.applyAction_ (E:\allure\qa_automation_camp\node_modules\protractor\built\element.js:459:27)
                    at ElementArrayFinder.(anonymous function).args [as click] (E:\allure\qa_automation_camp\node_modules\protractor\built\element.js:91:29)
                    at ElementFinder.(anonymous function).args [as click] (E:\allure\qa_automation_camp\node_modules\protractor\built\element.js:831:22)
                    at ProductsPage.create (E:\allure\qa_automation_camp\page_objects\products.page.js:22:37)
                    at process._tickCallback (internal/process/next_tick.js:68:7)
                From: Task: Run it("Login pass test") in control flow
                    at UserContext.&lt;anonymous> (E:\allure\qa_automation_camp\node_modules\jasminewd2\index.js:94:19)
                    at attempt (E:\allure\qa_automation_camp\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
                    at QueueRunner.run (E:\allure\qa_automation_camp\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
                    at QueueRunner.execute (E:\allure\qa_automation_camp\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
                    at Spec.queueRunnerFactory (E:\allure\qa_automation_camp\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
                    at Spec.execute (E:\allure\qa_automation_camp\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
                    at UserContext.fn (E:\allure\qa_automation_camp\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
                    at attempt (E:\allure\qa_automation_camp\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
                    at QueueRunner.run (E:\allure\qa_automation_camp\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
                    at runNext (E:\allure\qa_automation_camp\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
                From asynchronous test: 
                Error
                    at Suite.describe (E:\allure\qa_automation_camp\tests\login.spec.js:19:5)
                    at addSpecsToSuite (E:\allure\qa_automation_camp\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
                    at Env.describe (E:\allure\qa_automation_camp\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
                    at describe (E:\allure\qa_automation_camp\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
                    at Object.&lt;anonymous> (E:\allure\qa_automation_camp\tests\login.spec.js:4:1)
                    at Module._compile (internal/modules/cjs/loader.js:689:30)
                    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
                    at Module.load (internal/modules/cjs/loader.js:599:32)
                    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>