<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1536216032448' stop='1536216038424'>
    <name>Login suit:</name>
    <title>Login suit:</title>
    <test-cases>
        <test-case start='1536216032448' status='passed' stop='1536216036629'>
            <name>Login pass test</name>
            <title>Login pass test</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1536216036629' status='failed' stop='1536216038424'>
            <name>Login pass test</name>
            <title>Login pass test</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Failed: No element found using locator: By(css selector, button.btn.login-button)</message>
                <stack-trace>NoSuchElementError: No element found using locator: By(css selector, button.btn.login-button)
                    at elementArrayFinder.getWebElements.then (C:\Users\andrii.hnatyshyn\AppData\Roaming\npm\node_modules\protractor\built\element.js:814:27)
                    at ManagedPromise.invokeCallback_ (C:\Users\andrii.hnatyshyn\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
                    at TaskQueue.execute_ (C:\Users\andrii.hnatyshyn\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (C:\Users\andrii.hnatyshyn\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at asyncRun (C:\Users\andrii.hnatyshyn\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
                    at C:\Users\andrii.hnatyshyn\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
                    at process._tickCallback (internal/process/next_tick.js:68:7)Error
                    at ElementArrayFinder.applyAction_ (C:\Users\andrii.hnatyshyn\AppData\Roaming\npm\node_modules\protractor\built\element.js:459:27)
                    at ElementArrayFinder.(anonymous function).args [as click] (C:\Users\andrii.hnatyshyn\AppData\Roaming\npm\node_modules\protractor\built\element.js:91:29)
                    at ElementFinder.(anonymous function).args [as click] (C:\Users\andrii.hnatyshyn\AppData\Roaming\npm\node_modules\protractor\built\element.js:831:22)
                    at LoginPage.login (E:\allure\qa_automation_camp\page_objects\login.page.js:34:34)
                    at UserContext.it (E:\allure\qa_automation_camp\tests\login.spec.js:23:49)
                    at process._tickCallback (internal/process/next_tick.js:68:7)
                From: Task: Run it("Login pass test") in control flow
                    at UserContext.&lt;anonymous> (C:\Users\andrii.hnatyshyn\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
                    at attempt (C:\Users\andrii.hnatyshyn\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
                    at QueueRunner.run (C:\Users\andrii.hnatyshyn\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
                    at QueueRunner.execute (C:\Users\andrii.hnatyshyn\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
                    at Spec.queueRunnerFactory (C:\Users\andrii.hnatyshyn\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
                    at Spec.execute (C:\Users\andrii.hnatyshyn\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
                    at UserContext.fn (C:\Users\andrii.hnatyshyn\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
                    at attempt (C:\Users\andrii.hnatyshyn\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
                    at QueueRunner.run (C:\Users\andrii.hnatyshyn\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
                    at runNext (C:\Users\andrii.hnatyshyn\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
                From asynchronous test: 
                Error
                    at Suite.describe (E:\allure\qa_automation_camp\tests\login.spec.js:19:5)
                    at addSpecsToSuite (C:\Users\andrii.hnatyshyn\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
                    at Env.describe (C:\Users\andrii.hnatyshyn\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
                    at describe (C:\Users\andrii.hnatyshyn\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
                    at Object.&lt;anonymous> (E:\allure\qa_automation_camp\tests\login.spec.js:4:1)
                    at Module._compile (internal/modules/cjs/loader.js:689:30)
                    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
                    at Module.load (internal/modules/cjs/loader.js:599:32)
                    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>